use_frameworks!
platform :ios, '12.0'
workspace 'XInjectionIII.xcworkspace'




target 'SwiftTest' do
  pod 'XInjectionIII', :path => '../'
  project 'SwiftTest.xcodeproj'
end


target 'XInjectionIII_Example' do
  pod 'XInjectionIII', :path => '../'
  project 'XInjectionIII.xcodeproj'
end
